set_property IOSTANDARD LVCMOS33 [get_ports {out0[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {out0[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {out0[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports in0]
set_property IOSTANDARD LVCMOS33 [get_ports in1]
set_property IOSTANDARD LVCMOS33 [get_ports sel]
set_property PACKAGE_PIN M20 [get_ports sel]
set_property PACKAGE_PIN D19 [get_ports in0]
set_property PACKAGE_PIN D20 [get_ports in1]
set_property PACKAGE_PIN R14 [get_ports {out0[0]}]
set_property PACKAGE_PIN P14 [get_ports {out0[1]}]
set_property PACKAGE_PIN N16 [get_ports {out0[2]}]

set_property IOSTANDARD LVCMOS33 [get_ports {out0[3]}]
set_property PACKAGE_PIN M14 [get_ports {out0[3]}]
